source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’

target “Hephaestus” do
pod 'Masonry'
pod 'AFNetworking'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod "WeiboSDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git"
pod 'MJExtension'
pod 'SDWebImage'
end
